development:
  clients:
    default:
      database: resizephoto_api_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: resizephoto_api_test
      hosts:
        - localhost:27017
